config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "homes#index"
  
  resources :user_profiles, only: [:show] 
    
  post '/updated_wishlist_quantity', to: "user_profiles#updated_wishlist_quantity"

  resources :homes
  resources :carts
  resources :wishlists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :profile_img

  has_many :wishlists
  has_one :cart

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
   before_action :configure_permitted_parameters, if: :devise_controller?

   
   def after_sign_up_path_for(resource)
 	   edit_user_registration_path(resource)
   end

   def after_sign_in_path_for(resource)
 	   if resource.phone.blank? || resource.name.blank?
         edit_user_registration_path(resource)
 	   else
 	      super	
 	   end	
   end

   def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :profile_img, :address])
   end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def index
		@products = FetchDataService.new.get_product_ids(params[:id])
		@carts = current_user.carts.all
	end

	def new
		@carts = Cart.new
	end


	def create

		# byebug
		
		@carts = current_user.carts.new(product_id: params[:product_id])
	    @carts.save
        redirect_to homes_path
    
	end

	def destroy
		@cart = current_user.carts.find(params[:id])
		@cart.destroy
		redirect_to homes_path
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    
    @categories = FetchDataService.new.get_categories
    # byebug
    @products = FetchDataService.new.get_products(params[:category_id])
    
  end


end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController

  before_action :authenticate_user!, except: [:updated_wishlist_quantity]
  skip_before_action :verify_authenticity_token, only: [:updated_wishlist_quantity]

  def show
    @user = User.find_by_id(params[:id])
  end

  def updated_wishlist_quantity
    if params[:product_id].present?
      @wishlists = Wishlist.where(product_id: params[:product_id])
      @wishlists.each do |wishlist|
        UserMailer.with(user: wishlist.user).wishlist_email.deliver_later
      end
      render text: "ok"
    end
  end

  
  
    
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
	def index
		@products = FetchDataService.new.get_products(params[:category_id])
		@wishlists = current_user.wishlists.all
	end

	def new
		@wishlist = Wishlist.new
	end


	def create
		 # byebug

		@wishlist = current_user.wishlists.new(product_id: params[:product_id])
	    @wishlist.save
        redirect_to homes_path
    
	end

	def destroy
		@wishlist = current_user.wishlists.find(params[:id])
		@wishlist.destroy
		redirect_to homes_path
	end

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/carts/index.html.erb
<header>
    <%= render 'layouts/navigation' %>
</header>

<div class="container">
<center>
<h1>Cart</h1>
<table class="table table-hover" style="margin-top: 4em;width: 60rem;">
  <thead>
    <tr>
      <th scope="col">Product Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>

    
    <!-- < @carts.each do |cart| %> -->
    <% @products.each do |product| %>
    <tr>
      
        <!-- < if product["id"] == cart.product_id %> -->
          <td><%= product["attributes"]["name"] %></td>

          <td><%= number_field_tag :quantity, in: 1..10 %></td>

          <td><%= product["attributes"]["price"] %></td>
          <!-- <td><= link_to "Remove", cart, method: :delete, data: { confirm: "Are you sure?" } %></td> -->
          
        <!-- <end %> -->
      
    </tr>
    <% end %>
    <!-- < end %> -->
    <tr>
      <td>Total</td>
      <td></td>
    </tr>  
  </tbody>
</table>

<button id="rzp-button1">Checkout</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>

document.getElementById('rzp-button1').onclick = function(e){
  var options = {
    "key": "rzp_test_xgTnELp25UmLCC", 
    "amount": "4000", 
    "currency": "INR",
    "name": "Product App",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    // "order_id": "order_Hm8bfwmCeDBj7a",     #transaction done
    "order_id": "order_Hm93UBmfaTyqPi" ,
    "handler": function (response){
        alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature)
    },
    "prefill": {
        "name": "Yashi Birthare",
        "email": "yashib@witmates.com",
        "contact": "9999999999"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
    rzp1.open();
    e.preventDefault();
}
</script>

</center>
</div>

app/views/homes/index.html.erb
<% if user_signed_in? %>

  <header>
      <%= render 'layouts/navigation' %>
      <nav>
      <%= render 'layouts/side_navbar'%>
      </nav>
  </header>
  <div class="container">
    <center><h2 class="card-title">Products</h2></center>
    <div class="row">

    <% @products.each do |product| %>
    <div class="col-md-4">
    <div class="card" style="width: 14rem;margin-left: 12rem;margin-top: 1.5em;">
      <div class="card-body">
        <center><h5 class="card-title">Product</h5></center>
        <br>
        <h5>Name:</h5>
        <p><%= product["attributes"]["name"] %></p>
        <h5>Price:</h5>
        <p><%= product["attributes"]["price"] %></p>
        <% if product["attributes"]["quantity"].to_i.zero? %>
        
          <% unless current_user.wishlists.pluck(:product_id).include?(product["id"]) %>
            <%= link_to 'Add to Wishlist', '/wishlists?product_id=' + product["id"],method: :post, class: "btn btn-outline-success" %>
          <% else%>
            <p>Added to Wishlist</p>
          <% end %>

        <% else %>

          <% unless current_user.carts.pluck(:product_id).include?(product["id"]) %>
            <%= link_to 'Add to Cart', '/carts?product_id=' + product["id"],method: :post, class: "btn btn-outline-success" %>
          <% else%>
            <p>Added to Cart</p>
          <% end %>
        <% end %>
      </div>
    </div>
    </div>
    
    <% end %>
  </div>
  </div>
  

<% else %>
  <header>
      <%= render 'layouts/header' %>
  </header>

  <li>
  <%= link_to('Login', new_user_session_path) %>  
  </li>
  <li>
    <%= link_to('SignUp', new_user_registration_path) %>
  </li>
  
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Navbar</a>
    
    <button class="btn btn-outline-success btn-logout my-2 my-sm-0"><%= link_to('Login', new_user_session_path) %> </button> 
    <button class="btn btn-outline-success btn-logout my-2 my-sm-0"><%= link_to('SignUp', new_user_registration_path) %> </button>
    
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
 <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">User Dashboard</a>

      <%= link_to 'Profile', user_profile_path(current_user), class: "btn btn-outline-success btn-logout my-2 my-sm-0" %>
   
      <%= link_to 'Cart', carts_path, class: "btn btn-outline-success btn-space" %>
      <%= link_to 'Wishlist', wishlists_path, class: "btn btn-outline-success btn-space" %>

      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-success btn-logout my-2 my-sm-0" ) %> 
    
  </div>
</nav>

app/views/layouts/_side_navbar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li>
         <a href="#">Home</a>
      </li>
      <li class="dropdown">
        <a href="#">Categories</a>
        <ul class="dropdown-submenu" role="menu">
          <% @categories.each do |category| %>
            <li class="dropdown">
         
                <%= link_to category["attributes"]["name"],homes_path(category) %>
             
              <ul class="dropdown-submenu" role="menu">
                <% category["attributes"]["sub-categories"].each do |sub_cat| %>
                  <li>
                      <%= link_to sub_cat["name"],homes_path(sub_cat) %> 
                  
                  </li>
                <% end %>
              </ul>
            </li> 
          <% end %>
        </ul>
      </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    
  </body>
</html>

app/views/user_profiles/show.html.erb
<header>
  <%= render 'layouts/navigation' %>
</header>

<div class="card" style="width: 20rem;margin-left: 25rem;">
  <div class="card-body">
    <center><h5 class="card-title">User Profile</h5></center>
    <br>
    <label>Name:</label>
    <label><%= @user.name %></label>
    <br>
    <label>Email:</label>
    <label><%= @user.email %></label>
    <br>
    <label>Phone:</label>
    <label><%= @user.phone %></label>
    <br>
    <label>Image:</label>
    <%= image_tag @user.profile_img, style: "width:50px;" %>
    <br>
    <label>Address:</label>
    <label><%= @user.address %></label>
    <br><br>
    <center><button class="btn btn-outline-success my-2 my-sm-0"><%= link_to 'Update Profile', edit_user_registration_path %> </button></center>
  </div>
</div>

app/views/wishlists/index.html.erb
<header>
    <%= render 'layouts/navigation' %>
</header>

<div class="container">
<center>
<h1>Wishlist</h1>
<table class="table table-hover" style="margin-top: 4em;width: 60rem;">
  <thead>
    <tr>
      <th scope="col">Product Name</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>

    
    <% @wishlists.each do |wishlist| %>
    <tr>
      <% @products.each do |product| %>
        <% if product["id"] == wishlist.product_id %>
          <td><%= product["attributes"]["name"] %></td>
          <td><%= product["attributes"]["price"] %></td>
          <td><%= link_to "Remove", wishlist, method: :delete, data: { confirm: "Are you sure?" } %></td>
          
        <% end %>
      <% end %>
    </tr>
    <% end %>
 
  </tbody>
</table>
</center>
</div>